In [56]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
!wget -O ds2.zip https://www.dropbox.com/sh/aypq6h3254207bs/AACzMLvo-XtK9sYAAma6FW0la?dl=0&file_subpath=%2Famz_com-ecommerce_sample.csv&preview=DS+-+Assignment+Part+2+data+set.zip

--2022-11-24 12:08:31--  https://www.dropbox.com/sh/aypq6h3254207bs/AACzMLvo-XtK9sYAAma6FW0la?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /sh/raw/aypq6h3254207bs/AACzMLvo-XtK9sYAAma6FW0la [following]
--2022-11-24 12:08:32--  https://www.dropbox.com/sh/raw/aypq6h3254207bs/AACzMLvo-XtK9sYAAma6FW0la
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc0ee8c8fa5864496a468bdfaa19.dl.dropboxusercontent.com/zip_download_get/BUwOb8BjjKv0P-miVA6dsNPdBWPi2-sQjS-eX4VuSPjmwye1P2wC_2HD8le935cuiywQR6Vdr9Ef2zYoagBxpfSFtFvx5GUa7u9dPmoQR4aUTw# [following]
--2022-11-24 12:08:33--  https://uc0ee8c8fa5864496a468bdfaa19.dl.dropboxusercontent.com/zip_download_get/BUwOb8BjjKv0P-miVA6dsNPdBWPi2-sQjS-eX4VuSPjmwye1P2wC_2HD8le935cuiywQR6Vdr9Ef2zYoagBxpfSFtFvx

In [3]:
!unzip ds2.zip

Archive:  ds2.zip
mapname:  conversion of  failed
 extracting: Data Science Assignment.pdf  
 extracting: DS - Assignment Part 2 data set.zip  
 extracting: DS - Assignment Part 1 data set.xlsx  


In [5]:
!unzip '/content/DS - Assignment Part 2 data set.zip'y

Archive:  /content/DS - Assignment Part 2 data set.zip
  inflating: amz_com-ecommerce_sample.csv  
replace flipkart_com-ecommerce_sample.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: flipkart_com-ecommerce_sample.csv  


In [43]:
flp=pd.read_csv('/content/flipkart_com-ecommerce_sample.csv')
amz=pd.read_csv('/content/amz_com-ecommerce_sample.csv',encoding='latin1')

In [72]:
amz.duplicated().sum()

0

In [10]:
flp.head()

uniq_id            crawl_timestamp  \
0  c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1  7f7036a6d550aaa89d34c77bd39a5e48  2016-03-25 22:59:23 +0000   
2  f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
3  0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2FF9KEDEFGF   
1  ["Furniture >> Living Room Furniture >> Sofa B...  SBEEH3QGU7MFYJFY   
2  ["Footwear >> Women's Footwear >> Ballerinas >...  SHOEH4GRSUBJGZXE   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2F6HUZMQ6SJ   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...  PSOEH3ZYDMSYARJ5   

   retail_price  discounted_price  \
0         999.0             379.0   
1       32157.0           22646.0   
2         999.0             499.0   
3         699.0             267.0   
4         220.0             210.0   

                                               image  is_FK_Advantage_product  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...                    False   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...                    False   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...                    False   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...                    False   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...                    False   

                                         description       product_rating  \
0  Key Features of Alisha Solid Women's Cycling S...  No rating available   
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  No rating available   
2  Key Features of AW Bellies Sandals Wedges Heel...  No rating available   
3  Key Features of Alisha Solid Women's Cycling S...  No rating available   
4  Specifications of Sicons All Purpose Arnica Do...  No rating available   

        overall_rating         brand  \
0  No rating available        Alisha   
1  No rating available  FabHomeDecor   
2  No rating available            AW   
3  No rating available        Alisha   
4  No rating available        Sicons   

                              product_specifications  
0  {"product_specification"=>[{"key"=>"Number of ...  
1  {"product_specification"=>[{"key"=>"Installati...  
2  {"product_specification"=>[{"key"=>"Ideal For"...  
3  {"product_specification"=>[{"key"=>"Number of ...  
4  {"product_specification"=>[{"key"=>"Pet Type",...

In [11]:
amz.head()

uniq_id            crawl_timestamp  \
0  c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1  7f7036a6d550aaa89d34c77bd39a5e48  2016-03-25 22:59:23 +0000   
2  f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
3  0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2FF9KEDEFGF   
1  ["Furniture >> Living Room Furniture >> Sofa B...  SBEEH3QGU7MFYJFY   
2  ["Footwear >> Women's Footwear >> Ballerinas >...  SHOEH4GRSUBJGZXE   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2F6HUZMQ6SJ   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...  PSOEH3ZYDMSYARJ5   

   retail_price  discounted_price  \
0           982               438   
1         32143             29121   
2           991               551   
3           694               325   
4           208               258   

                                               image  is_FK_Advantage_product  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...                    False   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...                    False   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...                    False   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...                    False   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...                    False   

                                         description       product_rating  \
0  Key Features of Alisha Solid Women's Cycling S...  No rating available   
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  No rating available   
2  Key Features of AW Bellies Sandals Wedges Heel...  No rating available   
3  Key Features of Alisha Solid Women's Cycling S...  No rating available   
4  Specifications of Sicons All Purpose Arnica Do...  No rating available   

        overall_rating         brand  \
0  No rating available        Alisha   
1  No rating available  FabHomeDecor   
2  No rating available            AW   
3  No rating available        Alisha   
4  No rating available        Sicons   

                              product_specifications  
0  {"product_specification"=>[{"key"=>"Number of ...  
1  {"product_specification"=>[{"key"=>"Installati...  
2  {"product_specification"=>[{"key"=>"Ideal For"...  
3  {"product_specification"=>[{"key"=>"Number of ...  
4  {"product_specification"=>[{"key"=>"Pet Type",...

In [16]:
print(flp.shape,amz.shape)

(20000, 15) (20000, 15)


In [12]:
print(flp.columns)
print(amz.columns)

Index(['uniq_id', 'crawl_timestamp', 'product_url', 'product_name',
       'product_category_tree', 'pid', 'retail_price', 'discounted_price',
       'image', 'is_FK_Advantage_product', 'description', 'product_rating',
       'overall_rating', 'brand', 'product_specifications'],
      dtype='object')
Index(['uniq_id', 'crawl_timestamp', 'product_url', 'product_name',
       'product_category_tree', 'pid', 'retail_price', 'discounted_price',
       'image', 'is_FK_Advantage_product', 'description', 'product_rating',
       'overall_rating', 'brand', 'product_specifications'],
      dtype='object')


In [37]:
flp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   uniq_id                  20000 non-null  object 
 1   crawl_timestamp          20000 non-null  object 
 2   product_url              20000 non-null  object 
 3   product_name             20000 non-null  object 
 4   product_category_tree    20000 non-null  object 
 5   pid                      20000 non-null  object 
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  object 
 9   is_FK_Advantage_product  20000 non-null  bool   
 10  description              19998 non-null  object 
 11  product_rating           20000 non-null  object 
 12  overall_rating           20000 non-null  object 
 13  brand                    14136 non-null  object 
 14  product_specifications

In [41]:
amz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   uniq_id                  20000 non-null  object
 1   crawl_timestamp          20000 non-null  object
 2   product_url              20000 non-null  object
 3   product_name             20000 non-null  object
 4   product_category_tree    20000 non-null  object
 5   pid                      20000 non-null  object
 6   retail_price             20000 non-null  int64 
 7   discounted_price         20000 non-null  int64 
 8   image                    19997 non-null  object
 9   is_FK_Advantage_product  20000 non-null  bool  
 10  description              19998 non-null  object
 11  product_rating           20000 non-null  object
 12  overall_rating           20000 non-null  object
 13  brand                    14136 non-null  object
 14  product_specifications   19986 non-nul

In [44]:
# we will remove the rows that have missing brand
flp_new=flp.loc[flp['brand'].notnull()]
amz_new=amz.loc[amz['brand'].notnull()]
print(flp_new.shape,
amz_new.shape)

(14136, 15) (14136, 15)


In [50]:
#vectorizing brand name
vectorizer=TfidfVectorizer()
vectorizer.fit(pd.concat([flp_new['brand'],amz_new['brand']]))
flp_brand_vect=vectorizer.transform(flp_new['brand'])
amz_brand_vect=vectorizer.transform(amz_new['brand'])

In [51]:
print(flp_brand_vect.shape)
print(amz_brand_vect.shape)

(14136, 3595)
(14136, 3595)


In [52]:
#vectorizing product name
vectorizer=TfidfVectorizer()
vectorizer.fit(pd.concat([flp_new['product_name'],amz_new['product_name']]))
flp_product_vect=vectorizer.transform(flp_new['product_name'])
amz_product_vect=vectorizer.transform(amz_new['product_name'])

In [53]:
print(flp_product_vect.shape,amz_product_vect.shape)

(14136, 9854) (14136, 9854)


In [55]:
flp_vect=np.hstack([flp_brand_vect.toarray(),flp_product_vect.toarray()])
amz_vect=np.hstack([amz_brand_vect.toarray(),amz_product_vect.toarray()])
print(flp_vect.shape,amz_vect.shape)

(14136, 13449) (14136, 13449)


In [60]:
cosine_sim=cosine_similarity(flp_vect,amz_vect)
print(cosine_sim)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]


In [94]:
def similar_product(flipkart_product_name,sim_matrix,flipkart_dataset,amazon_dataset):
  name=flipkart_product_name
  flp_index=flipkart_dataset.loc[flipkart_dataset['product_name']==name].index[0]  #getting the index of row where product name matches in amazon datset
  amz_index=np.argmax(sim_matrix[flp_index])                                       #getting the index of row where product name matches in amazon dataset
  print('Product name in Flipkart :',flipkart_dataset.iloc[flp_index]['product_name'])
  print('Retail Price in Flipkart :',flipkart_dataset.iloc[flp_index]['retail_price'])
  print('Discounted Price in Flipkart :',flipkart_dataset.iloc[flp_index]['discounted_price'])
  print('-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*')
  print('Product name in Amazon :',amazon_dataset.iloc[amz_index]['product_name'])
  print('Retail Price in Amazon :',amazon_dataset.iloc[amz_index]['retail_price'])
  print('Discounted Price in Amazon :',amazon_dataset.iloc[amz_index]['discounted_price'])

In [101]:
flp_new.reset_index(inplace=True)
amz_new.reset_index(inplace=True)

In [102]:
similar_product('Tenda TE-W368R',cosine_sim,flp_new,amz_new)

Product name in Flipkart : Tenda TE-W368R
Retail Price in Flipkart : 2200.0
Discounted Price in Flipkart : 1546.0
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
Product name in Amazon : Tenda TE-W368R
Retail Price in Amazon : 2188
Discounted Price in Amazon : 1988
